name: OSM Places Scan

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours; adjust if you like
  workflow_dispatch:

permissions:
  contents: write

# Prevent overlapping runs (never cancel an in-progress job)
concurrency:
  group: osm-places-scan
  cancel-in-progress: false

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 330   # ~5.5h job window
    env:
      MAX_JOB_SECONDS: "16200"   # 4.5h; leaves ~1h for setup + commit/push
      BATCH_SIZE: "1000000"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run batch (cursor-aware, timed)
        run: python3 runner_local.py

      - name: Commit outputs, cursor, and dedupe
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add outputs/**/*.csv outputs/*.csv cursor.json state_dedupe.jsonl || true
          git commit -m "OSM batch $(date -u +'%Y-%m-%d %H:%M:%S') UTC" || echo "Nothing to commit"
          git push
