name: US Places Scan

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours; adjust as you like
  workflow_dispatch:        # allow manual run

permissions:
  contents: write           # needed to commit outputs/dedupe back to repo

jobs:
  scan:
    runs-on: ubuntu-latest
    env:
      BATCH_SIZE: "5"       # process 5 locations per run to keep costs low
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Inject API key into config.py
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        run: |
          # Replace the API_KEY line in config.py with the secret at runtime
          python - << 'PY'
import re, pathlib, os
p = pathlib.Path("config.py")
s = p.read_text()
s = re.sub(r'^API_KEY\s*=\s*.*?$', f'API_KEY = "{os.environ["GOOGLE_MAPS_API_KEY"]}"', s, flags=re.M)
p.write_text(s)
print("API key injected.")
PY

      - name: Run batch
        run: python runner_local.py

      - name: Commit outputs and dedupe
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add outputs/*.csv state_dedupe.jsonl || true
          git commit -m "Automated batch $(date -u +'%Y-%m-%d %H:%M:%S') UTC" || echo "Nothing to commit"
          git push
