name: US Places Scan

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scan:
    runs-on: ubuntu-latest
    env:
      BATCH_SIZE: "5"       # process N locations per run to control cost
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Inject API key into config.py
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        run: |
          python -c "import re, pathlib, os; p=pathlib.Path('config.py'); s=p.read_text(); s=re.sub(r'^API_KEY\\s*=\\s*.*?$', f'API_KEY = \"{os.environ.get(\"GOOGLE_MAPS_API_KEY\",\"\")}\"', s, flags=re.M); p.write_text(s); print('API key injected.')"

      - name: Run batch
        run: python runner_local.py

      - name: Commit outputs and dedupe
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add outputs/*.csv state_dedupe.jsonl cursor.json || true
          git commit -m "Automated batch $(date -u +'%Y-%m-%d %H:%M:%S') UTC" || echo "Nothing to commit"
          git push
